# Generated by Django 2.0.7 on 2018-08-18 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(choices=[('FR', '301'), ('SC', 'Boot C in 302'), ('SD', 'Boot D in 302'), ('SB', 'Boot B in 302'), ('SA', 'Boot A in 302'), ('ST', 'All Boots(ABCD) in 302')], max_length=2)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(choices=[('SP', 'Speaker'), ('MC', 'iMac'), ('PT', 'Printer'), ('DT', 'Ddesktop'), ('EP', 'EarPhone')], max_length=2)),
                ('status', models.CharField(choices=[('SB', 'Slightly Broken'), ('PF', 'Perfect'), ('TB', 'Toltally Broken')], max_length=2)),
                ('device_id', models.IntegerField(unique=True)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='RoomToUse',
            field=models.ManyToManyField(blank=True, to='borrow.Room'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='StuffToUse',
            field=models.ManyToManyField(blank=True, to='borrow.Stuff'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
