# Generated by Django 2.0.6 on 2018-09-25 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('is_approved', models.BooleanField(default=False)),
                ('OtherRequests', models.CharField(blank=True, default='无', max_length=100)),
                ('ErrorMessage', models.CharField(default=' ', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(choices=[('SC', 'Boot C in 302'), ('SA', 'Boot A in 302'), ('ST', 'All Boots(ABCD) in 302'), ('FR', '301'), ('SB', 'Boot B in 302'), ('SD', 'Boot D in 302')], max_length=2)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.CharField(choices=[('DT', 'Ddesktop'), ('EP', 'EarPhone'), ('PT', 'Printer'), ('SP', 'Speaker'), ('MC', 'iMac')], max_length=20)),
                ('status', models.CharField(choices=[('SB', 'Slightly Broken'), ('TB', 'Toltally Broken'), ('PF', 'Perfect')], max_length=2)),
                ('device_id', models.IntegerField(unique=True)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='RoomToUse',
            field=models.ManyToManyField(blank=True, to='borrow.Room'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='StuffToUse',
            field=models.ManyToManyField(blank=True, related_name='common', to='borrow.Stuff'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
