# Generated by Django 2.0.7 on 2018-08-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='spec',
            field=models.CharField(choices=[('SA', 'Boot A in 302'), ('SC', 'Boot C in 302'), ('FR', '301'), ('ST', 'All Boots(ABCD) in 302'), ('SD', 'Boot D in 302'), ('SB', 'Boot B in 302')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='spec',
            field=models.CharField(choices=[('EP', 'EarPhone'), ('PT', 'Printer'), ('DT', 'Ddesktop'), ('SP', 'Speaker'), ('MC', 'iMac')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='status',
            field=models.CharField(choices=[('PF', 'Perfect'), ('TB', 'Toltally Broken'), ('SB', 'Slightly Broken')], max_length=2),
        ),
    ]
