# Generated by Django 2.0.6 on 2018-09-27 06:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='ErrorMessage',
            field=models.CharField(blank=True, default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='spec',
            field=models.CharField(choices=[('SB', 'Boot B in 302'), ('SA', 'Boot A in 302'), ('FR', '301'), ('SD', 'Boot D in 302'), ('ST', 'All Boots(ABCD) in 302'), ('SC', 'Boot C in 302')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='spec',
            field=models.CharField(choices=[('EP', 'EarPhone'), ('MC', 'iMac'), ('DT', 'Ddesktop'), ('PT', 'Printer'), ('SP', 'Speaker')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='status',
            field=models.CharField(choices=[('PF', 'Perfect'), ('TB', 'Toltally Broken'), ('SB', 'Slightly Broken')], max_length=2),
        ),
    ]
