# Generated by Django 2.0.7 on 2018-08-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='spec',
            field=models.CharField(choices=[('SB', 'Boot B in 302'), ('SC', 'Boot C in 302'), ('ST', 'All Boots(ABCD) in 302'), ('FR', '301'), ('SD', 'Boot D in 302'), ('SA', 'Boot A in 302')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='spec',
            field=models.CharField(choices=[('DT', 'Ddesktop'), ('SP', 'Speaker'), ('PT', 'Printer'), ('EP', 'EarPhone'), ('MC', 'iMac')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='status',
            field=models.CharField(choices=[('SB', 'Slightly Broken'), ('TB', 'Toltally Broken'), ('PF', 'Perfect')], max_length=2),
        ),
    ]
