# Generated by Django 2.0.7 on 2018-08-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_auto_20180818_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='spec',
            field=models.CharField(choices=[('SD', 'Boot D in 302'), ('ST', 'All Boots(ABCD) in 302'), ('SC', 'Boot C in 302'), ('SA', 'Boot A in 302'), ('SB', 'Boot B in 302'), ('FR', '301')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='spec',
            field=models.CharField(choices=[('EP', 'EarPhone'), ('PT', 'Printer'), ('MC', 'iMac'), ('DT', 'Ddesktop'), ('SP', 'Speaker')], max_length=2),
        ),
    ]
