# Generated by Django 2.0.7 on 2018-08-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_auto_20180826_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='spec',
            field=models.CharField(choices=[('SB', 'Boot B in 302'), ('SA', 'Boot A in 302'), ('SC', 'Boot C in 302'), ('FR', '301'), ('ST', 'All Boots(ABCD) in 302'), ('SD', 'Boot D in 302')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='spec',
            field=models.CharField(choices=[('DT', 'Ddesktop'), ('SP', 'Speaker'), ('EP', 'EarPhone'), ('MC', 'iMac'), ('PT', 'Printer')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='status',
            field=models.CharField(choices=[('SB', 'Slightly Broken'), ('PF', 'Perfect'), ('TB', 'Toltally Broken')], max_length=2),
        ),
    ]
