# Generated by Django 2.0.6 on 2018-09-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_auto_20180927_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='spec',
            field=models.CharField(choices=[('SA', 'Boot A in 302'), ('SC', 'Boot C in 302'), ('SB', 'Boot B in 302'), ('FR', '301'), ('SD', 'Boot D in 302'), ('ST', 'All Boots(ABCD) in 302')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='spec',
            field=models.CharField(choices=[('MC', 'iMac'), ('SP', 'Speaker'), ('PT', 'Printer'), ('DT', 'Ddesktop'), ('EP', 'EarPhone')], max_length=20),
        ),
    ]
