# Generated by Django 2.0.7 on 2018-09-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_auto_20180828_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='spec',
            field=models.CharField(choices=[('SA', 'Boot A in 302'), ('SB', 'Boot B in 302'), ('SC', 'Boot C in 302'), ('FR', '301'), ('SD', 'Boot D in 302'), ('ST', 'All Boots(ABCD) in 302')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='spec',
            field=models.CharField(choices=[('MC', 'iMac'), ('EP', 'EarPhone'), ('PT', 'Printer'), ('SP', 'Speaker'), ('DT', 'Ddesktop')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='status',
            field=models.CharField(choices=[('SB', 'Slightly Broken'), ('TB', 'Toltally Broken'), ('PF', 'Perfect')], max_length=2),
        ),
    ]
