# Generated by Django 2.0.7 on 2018-09-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_auto_20180922_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='spec',
            field=models.CharField(choices=[('SA', 'Boot A in 302'), ('FR', '301'), ('SB', 'Boot B in 302'), ('ST', 'All Boots(ABCD) in 302'), ('SC', 'Boot C in 302'), ('SD', 'Boot D in 302')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='spec',
            field=models.CharField(choices=[('PT', 'Printer'), ('EP', 'EarPhone'), ('SP', 'Speaker'), ('DT', 'Ddesktop'), ('MC', 'iMac')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='status',
            field=models.CharField(choices=[('SB', 'Slightly Broken'), ('PF', 'Perfect'), ('TB', 'Toltally Broken')], max_length=2),
        ),
    ]
