# Generated by Django 2.0.7 on 2018-09-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0009_auto_20180922_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='spec',
            field=models.CharField(choices=[('FR', '301'), ('SB', 'Boot B in 302'), ('SA', 'Boot A in 302'), ('ST', 'All Boots(ABCD) in 302'), ('SC', 'Boot C in 302'), ('SD', 'Boot D in 302')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='spec',
            field=models.CharField(choices=[('MC', 'iMac'), ('PT', 'Printer'), ('DT', 'Ddesktop'), ('EP', 'EarPhone'), ('SP', 'Speaker')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='status',
            field=models.CharField(choices=[('TB', 'Toltally Broken'), ('SB', 'Slightly Broken'), ('PF', 'Perfect')], max_length=2),
        ),
    ]
