# Generated by Django 2.0.7 on 2018-09-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0014_auto_20180923_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='ApplyTime',
        ),
        migrations.AlterField(
            model_name='room',
            name='spec',
            field=models.CharField(choices=[('SB', 'Boot B in 302'), ('SC', 'Boot C in 302'), ('FR', '301'), ('ST', 'All Boots(ABCD) in 302'), ('SD', 'Boot D in 302'), ('SA', 'Boot A in 302')], max_length=2),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='spec',
            field=models.CharField(choices=[('DT', 'Ddesktop'), ('MC', 'iMac'), ('SP', 'Speaker'), ('EP', 'EarPhone'), ('PT', 'Printer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='status',
            field=models.CharField(choices=[('PF', 'Perfect'), ('SB', 'Slightly Broken'), ('TB', 'Toltally Broken')], max_length=2),
        ),
    ]
